### PR TITLE
Fix tests for macOS arp fix

### PR DESCRIPTION
**Pull request by raymanP**
### All Submissions:

- [x] Have you followed the guidelines in our Contributing document?
- [x] Have you checked to ensure there aren't other open [Pull Requests](../../pulls) for the same update/change?
- [x] Have you added an explanation of what your changes do and why you'd like us to include them?

### Code changes:

- [x] Did you format your code with Black? 
    - `black getmac tests`
- [x] Are the linting checks passing?
    - `tox -e check`
- [x] Do all tests pass locally?
    - `tox`
- [x] Have you updated the [CHANGELOG](CHANGELOG.md) with a summary of your change?
- [x] Did you add your name to the contributors list in the [README](README.md)?

### Summary of changes:
-

### CODE REVIEW

**Comment by raymanP** [comment]
Python 2.7 seems not to be functional anymore
Could be good to remove it's support here as done in 1.0.0-wip?

**Comment by GhostofGoes** [comment]
@raymanP Hey, really sorry this languished for so long. I had a lot going on at the start of the year and this fell through the cracks. 2.7 has been removed from the tests in main, if you pull those in this branch should pass.

**Review by GhostofGoes — APPROVED** [review]

**Comment by raymanP** [comment]
Hi @GhostofGoes , no problem, good you're back!
I updated, however, it seems there is a general CI problem for Python 3.5 and for the macos tests now.
I don't know how to handle this. Hope u can find time to adress this.

**Comment by GhostofGoes** [comment]
> Hi @GhostofGoes , no problem, good you're back! I updated, however, it seems there is a general CI problem for Python 3.5 and for the macos tests now. I don't know how to handle this. Hope u can find time to adress this.

Yeah, it's due to them being old enough that their OpenSSL version is too outdated. I'm just going to remove 3.5 and 3.6 from the tests as well as I'll be dropping support for them later anyway.

**Comment by GhostofGoes** [comment]
The MacOS tests for 3.7+ shoudn't be failing though. Might be an issue with GitHub actions...will see what happens on main.

**Comment by GhostofGoes** [comment]
Yup, it was due to Apple Silicon. Give it another try.

**Comment by raymanP** [comment]
Wonderful, everythin passed! )

**Pull request merged**
