### PR TITLE
Fix for Android 6.0.1

### PR DESCRIPTION
**Pull request by emadmahdi**
Tested and working.
Android 6.0.1
no need for root

### All Submissions:

* [ ] Have you followed the guidelines in our Contributing document?
* [ ] Have you checked to ensure there aren't other open [Pull Requests](../../pulls) for the same update/change?
* [ ] Have you added an explanation of what your changes do and why you'd like us to include them?

### Code changes:

* [ ] Did you format your code with Black? 
    * [ ] `black getmac tests`
* [ ] Are the linting checks passing?
    * [ ] `tox -e check`
* [ ] Do all tests pass locally?
    * [ ] `tox`
* [ ] Have you updated the [CHANGELOG](CHANGELOG.md) with a summary of your change?
* [ ] Did you add your name to the contributors list in the [README](README.md)?

### Summary of changes:
*

### CODE REVIEW

**Comment by GhostofGoes** [comment]
Looks good. Would you mind capturing samples of the output so I can add them to the tests? Just copy-paste the output of the command and put it in a test file in ./tests/samples/

**Comment by emadmahdi** [comment]
Done .. I added two files for two android commands.

Just to let you know ... I am using your getmac with my changes in a small project of mine which is currently used by over 600 device worldwide .. and getmac proved to be a very good replacement of uuid.

Thank you.

**Comment by emadmahdi** [comment]
The 600 devices are mostly windows and android .. but i also have other operating systems using getmac perfactly.

If you are interested to create a new uuid python module ... i can send you my script that convert the mac address to an id that consist of all numbers .. plus the new id have an extra 4 digits that works similar to checksum to verify this new id against any manipulation.

**Comment by GhostofGoes** [comment]
> Done .. I added two files for two android commands.

I think you might've forgotten to push the changes.

**Comment by GhostofGoes** [comment]
> Just to let you know ... I am using your getmac with my changes in a small non-commercial project which is currently used by over 600 device worldwide .. and getmac proved to be a very good replacement of uuid .. i can confirm that getmac is producing a unique id of all these devices with no exceptions.
> 
> Thank you.

Wow that's awesome! Thank you so much for sharing that, I love hearing how it gets used and that it helps people out 😁

**Comment by emadmahdi** [comment]
I am using github web .. I did not find a way to push my commits to your code ... I think you have to pull these changes and merge them with your code .. I have two pulls (branches) that needs to be merged to your code "patch-1"  and  "patch-2"

**Comment by GhostofGoes** [comment]
May open the second branch as a new PR? Unfortunately I don't use GitHub web much.

**Comment by emadmahdi** [comment]
I think you forgot to merege "patch-2"  .. it contains the two samples files .. while "patch-1" which already merged contains the modification of "getmac.py" file
emadmahdi/getmac:patch-2

**Comment by GhostofGoes** [comment]
The only PR I see is this one for `patch-1`, I don't see a PR for `patch-2`. Could you open a new PR from the patch-2 branch?

**Pull request merged**
